# Generated by Django 5.2 on 2025-05-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioCumplimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(max_length=200, unique=True)),
                ('definicion', models.TextField(blank=True, null=True)),
                ('importancia', models.TextField(blank=True, null=True)),
                ('como_obtenerlo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_general', models.TextField(blank=True, null=True)),
                ('sujeto_activo', models.CharField(blank=True, max_length=200, null=True)),
                ('sujeto_pasivo', models.CharField(blank=True, max_length=200, null=True)),
                ('alicuota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conceptos_clave_relacionados', models.ManyToManyField(blank=True, related_name='impuestos', to='servicios.conceptoclave')),
            ],
        ),
        migrations.CreateModel(
            name='Obligacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('plazo_general', models.CharField(blank=True, max_length=100, null=True)),
                ('requisitos_principales', models.TextField(blank=True, null=True)),
                ('impuestos_relacionados', models.ManyToManyField(blank=True, related_name='obligaciones', to='servicios.impuesto')),
            ],
        ),
        migrations.AddField(
            model_name='impuesto',
            name='obligaciones_relacionadas',
            field=models.ManyToManyField(blank=True, related_name='impuestos', to='servicios.obligacion'),
        ),
    ]
