# Generated by Django 5.2 on 2025-06-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impuesto',
            old_name='conceptos_clave_relacionados',
            new_name='conceptos_clave',
        ),
        migrations.RenameField(
            model_name='impuesto',
            old_name='obligaciones_relacionadas',
            new_name='obligaciones',
        ),
        migrations.RemoveField(
            model_name='obligacion',
            name='impuestos_relacionados',
        ),
        migrations.AddField(
            model_name='impuesto',
            name='beneficios',
            field=models.ManyToManyField(blank=True, related_name='impuestos', to='servicios.beneficiocumplimiento'),
        ),
        migrations.AddField(
            model_name='impuesto',
            name='preguntas_frecuentes',
            field=models.ManyToManyField(blank=True, related_name='impuestos', to='servicios.preguntafrecuente'),
        ),
    ]
