# Generated by Django 5.2 on 2025-06-08 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_rename_conceptos_clave_relacionados_impuesto_conceptos_clave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impuesto',
            name='alicuota',
        ),
        migrations.RemoveField(
            model_name='impuesto',
            name='beneficios',
        ),
        migrations.RemoveField(
            model_name='impuesto',
            name='conceptos_clave',
        ),
        migrations.RemoveField(
            model_name='impuesto',
            name='descripcion_general',
        ),
        migrations.RemoveField(
            model_name='impuesto',
            name='obligaciones',
        ),
        migrations.RemoveField(
            model_name='impuesto',
            name='preguntas_frecuentes',
        ),
        migrations.RemoveField(
            model_name='impuesto',
            name='sigla',
        ),
        migrations.RemoveField(
            model_name='impuesto',
            name='sujeto_activo',
        ),
        migrations.RemoveField(
            model_name='impuesto',
            name='sujeto_pasivo',
        ),
        migrations.AddField(
            model_name='beneficiocumplimiento',
            name='impuesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='beneficios', to='servicios.impuesto'),
        ),
        migrations.AddField(
            model_name='beneficiocumplimiento',
            name='nombre',
            field=models.CharField(db_index=True, default='Beneficio desconocido', max_length=100, verbose_name='Nombre del beneficio'),
        ),
        migrations.AddField(
            model_name='beneficiocumplimiento',
            name='url_detalle',
            field=models.URLField(blank=True, null=True, verbose_name='Más información'),
        ),
        migrations.AddField(
            model_name='conceptoclave',
            name='impuesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_clave', to='servicios.impuesto'),
        ),
        migrations.AddField(
            model_name='conceptoclave',
            name='url_fuente',
            field=models.URLField(blank=True, null=True, verbose_name='Fuente externa'),
        ),
        migrations.AddField(
            model_name='impuesto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='obligacion',
            name='impuesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='servicios.impuesto'),
        ),
        migrations.AddField(
            model_name='obligacion',
            name='url_info',
            field=models.URLField(blank=True, null=True, verbose_name='Información oficial'),
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='impuesto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='preguntas_frecuentes', to='servicios.impuesto'),
        ),
        migrations.AddField(
            model_name='preguntafrecuente',
            name='url_referencia',
            field=models.URLField(blank=True, null=True, verbose_name='Referencia externa'),
        ),
        migrations.AlterField(
            model_name='beneficiocumplimiento',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='beneficiocumplimiento',
            name='detalle',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle adicional'),
        ),
        migrations.AlterField(
            model_name='conceptoclave',
            name='como_obtenerlo',
            field=models.TextField(blank=True, null=True, verbose_name='Cómo obtenerlo'),
        ),
        migrations.AlterField(
            model_name='conceptoclave',
            name='definicion',
            field=models.TextField(default='Definición no disponible', verbose_name='Definición'),
        ),
        migrations.AlterField(
            model_name='conceptoclave',
            name='importancia',
            field=models.TextField(blank=True, null=True, verbose_name='Importancia'),
        ),
        migrations.AlterField(
            model_name='conceptoclave',
            name='termino',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Término clave'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre del impuesto'),
        ),
        migrations.AlterField(
            model_name='obligacion',
            name='descripcion',
            field=models.TextField(default='Sin descripción disponible', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='obligacion',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nombre de la obligación'),
        ),
        migrations.AlterField(
            model_name='obligacion',
            name='plazo_general',
            field=models.TextField(blank=True, null=True, verbose_name='Plazo general'),
        ),
        migrations.AlterField(
            model_name='obligacion',
            name='requisitos_principales',
            field=models.TextField(blank=True, null=True, verbose_name='Requisitos principales'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='pregunta',
            field=models.TextField(db_index=True, verbose_name='Pregunta frecuente'),
        ),
        migrations.AlterField(
            model_name='preguntafrecuente',
            name='respuesta',
            field=models.TextField(verbose_name='Respuesta'),
        ),
    ]
